サンプルページに『海外の旅〔上〕』を追加
vivliostyle/vivliostyle.org pull request #137
Opened 2023-06-07 14:44 UTC by yamasy1549

「段組／図版の段抜き配置」セクションの後に追加しました。

@ogwata @MurakamiShinyu 英語の部分に自信がないので確認をお願いしたいです :bow:

日本語：
<img width="1123" alt="image" src="https://github.com/vivliostyle/vivliostyle.org/assets/7820884/a371349f-b51e-4e01-9cc1-15882fe9b070">

英語：
<img width="1079" alt="image" src="https://github.com/vivliostyle/vivliostyle.org/assets/7820884/8cf62de9-f111-457d-b37e-a7ad68a678b8">

2023-06-07 15:37 UTC, MurakamiShinyu requested changes

2023-06-07 15:37 UTC, MurakamiShinyu commented on _data/sample.yml
> +      en: Horizontal books with a lot of figures
```suggestion
      en: Books with many figures
```

英語では本は横組にきまってるし「Horizontal books」ではhorizontal writing modeの本のことだと分からないでしょうから「横組書籍」は単に「Books」とするのがよいでしょう。それから "Books with a lot of figures" よりも "Books with many figures" のほうがよさそうです（Google検索での件数などから）。

2023-06-07 15:37 UTC, MurakamiShinyu commented on _data/sample.yml
> +          en: “Travel Abroad (The first volume)”
```suggestion
          en: “Travels Abroad (Volume 1)”
```

複数の旅の記録なので複数形Travelsに。

2023-06-07 16:22 UTC, MurakamiShinyu commented
タグは、「図版」が新設されてますが図版の配置にはページフロートを使っているし「ページフロート」というタグがすでにあるのだから「図版」ではなく「ページフロート」がよいかと思います。
それから、「ページヘッダー」と「複数HTML」も該当するのでそれらのタグも入れてよいと思います。

2023-06-08 03:11 UTC, ogwata reviewed
Apollo 8にならって、以下のような文言をp要素で入れた方がよいと思います。

ブラウザーの実装の差異によりページの食い違いがおこります。必ずChromeで閲覧してください。

2023-06-08 03:31 UTC, MurakamiShinyu commented
> Apollo 8にならって、以下のような文言をp要素で入れた方がよいと思います。
> ブラウザーの実装の差異によりページの食い違いがおこります。必ずChromeで閲覧してください。


そのような文言を入れることには反対です。
Chromeであっても使用されるフォントが違えば改行・改ページ位置は変わります。
Vivliostyle Viewerで見るサンプルはどれも固定レイアウト（改行・改ページが変わらない）であることを保証するものではありません。

改行・改ページが変わるだけでなく、正常に読めないようにレイアウトが崩れるのであれば、それはVivliostyleのバグです。

Vivliostyle Viewerは、Chromeに限らずどのブラウザでも利用できることが利点ですので、「必ずChromeで閲覧」などということを書くべきではありません。
もし別のブラウザで閲覧してレイアウト不具合が起きるのであれば、その不具合を直すことが必要です（Vivliostyleのバグを直す、あるいは公開サンプルをそのバグを回避するように修正する）。

2023-06-08 03:51 UTC, ogwata commented
> そのような文言を入れることには反対です。 Chromeであっても使用されるフォントが違えば改行・改ページ位置は変わります。 Vivliostyle Viewerで見るサンプルはどれも固定レイアウト（改行・改ページが変わらない）であることを保証するものではありません。

この本の多くのページは、見開き2ページで収まるようレイアウトしています。その意味でブラウザによる表示が起こりやすいと言えます。

実際にChrome、Firefox、Safariで見比べてみたところ、思っていた以上にページの食い違いがたくさん発生していることに気付きました。

つまり、Firefox、Safariのユーザがこのページを見た場合、誤解、混乱が広がってしまう可能性が高いのです。この文言にこだわりませんが、少なくともブラウザによる表示の違いについて何らかの注意喚起が必要ではないでしょうか。

2023-06-08 07:47 UTC, ogwata commented
少し手直しして、英文も考えてみました。


この本はChromeで最適な組版結果になるように作成しました。それ以外のブラウザでは一部レイアウトが変わることがあります。

This book was designed to achieve the best typesetting results in Chrome. Layout may be altered in some parts when viewed in other browsers.

2023-06-17 08:12 UTC, merged