Add blog post about online.tex 2020
vivliostyle/vivliostyle.org pull request #59
Opened 2020-12-18 15:07 UTC by ogwata

まず日本語文を作成しました。問題がなければ英訳に進みます。

2020-12-19 05:42 UTC, MurakamiShinyu commented on _posts/ja/2020-12-21-Update-on-the-development-of-Vivliostyle-at-Online.tex-2020.md
> +お恥ずかしいことに、これは私のケアレスミスです。本来、VFMでは段落区切り（ハード改行）はリターン2つです。なのに当日私がデモで使った原稿は、1つしか入っていませんでした。この場合GFMなどでは無視するのですが、VFMの場合は段落区切りではないソフト改行と解釈され、HTMLでは｀<br />｀に変換されます（上図）。
```
HTMLでは｀<br />｀に変換されます
```

'｀' (‎U+FF40 FULLWIDTH GRAVE ACCENT) になってます。次のように直すとよいでしょう：

```
HTMLでは `<br>` に変換されます
```

2020-12-19 05:51 UTC, MurakamiShinyu commented on _posts/ja/2020-12-21-Update-on-the-development-of-Vivliostyle-at-Online.tex-2020.md
> +使えません。これについてIssue登録しました。
「使えません」ではなく、HTMLでルビを記述すれば使えるということを書いたほうがよいと思います。markdownはもともとHTMLの簡易記法であって、簡易記法では書けないことは本来の記法で書けばよいという思想のものだと思います。

2020-12-21 06:38 UTC, ogwata commented on _posts/ja/2020-12-21-Update-on-the-development-of-Vivliostyle-at-Online.tex-2020.md
> +使えません。これについてIssue登録しました。
修正してみました。ご確認ください。

2020-12-21 07:14 UTC, MurakamiShinyu requested changes

2020-12-21 07:14 UTC, MurakamiShinyu commented on _posts/ja/2020-12-21-Update-on-the-development-of-Vivliostyle-at-Online.tex-2020.md
> +- [5. エディタのカーソル位置が、プレビュー画面で表示されるとよい](#5. エディタのカーソル位置が、プレビュー画面で表示されるとよい)
リンクがNGです。

Jekyllでの見出しから自動ID生成では、スペースはハイフン "-" に置き換わり、区切り記号類は削除されます。

"5. エディタのカーソル位置が、プレビュー画面で表示されるとよい" → "5-エディタのカーソル位置がプレビュー画面で表示されるとよい" など。

2020-12-21 09:28 UTC, ogwata commented
今回、見出しH2を使おうとしたのですが、文字サイズが大きすぎて見づらく、やむなくH3にしてあります。まだ大きすぎで、H4にしてもよかったかも。

ただ、セマンティックではありません。今までブログで見出しは使わなかったので気付きませんでしたが、このあたりのフォーマットを変更するにはどうすればよいでしょうか？

2020-12-21 15:32 UTC, MurakamiShinyu approved these changes

2020-12-21 15:34 UTC, merged