ブログ英語ページの追加
vivliostyle/vivliostyle.org pull request #63
Opened 2021-01-06 15:57 UTC by ogwata

確認をお願いします。

2021-01-07 01:47 UTC, MurakamiShinyu commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +title: New Year's Message and Update on Vivliostyle
Why not "New Year's Greetings and Updates on Vivliostyle" ?

2021-01-07 01:47 UTC, MurakamiShinyu commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +Last year Vivliostyle has been steadily updating and adding features. Originally, We should have announced the release on this blog, but We ware unable to do so last year. So We'd like to give you a
"We"-->"we"?

2021-01-07 01:47 UTC, MurakamiShinyu commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +First of all, the update history of [vivliostyle.js](https://github.com/vivliostyle/vivliostyle.js), which is the foundation of the entire project, can be found on the [GitHub release history page](h
Remove space in URL `github. com`

2021-01-07 02:54 UTC, ogwata commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +title: New Year's Message and Update on Vivliostyle
I chose "message" as it is simpler and conveys the intent better. Does this mean that "greeting" has more merit?

2021-01-07 02:56 UTC, ogwata commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +Last year Vivliostyle has been steadily updating and adding features. Originally, We should have announced the release on this blog, but We ware unable to do so last year. So We'd like to give you a
Thank you. It was an oversight.

2021-01-07 02:59 UTC, ogwata commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +First of all, the update history of [vivliostyle.js](https://github.com/vivliostyle/vivliostyle.js), which is the foundation of the entire project, can be found on the [GitHub release history page](h
This was also an oversight.

2021-01-07 10:35 UTC, johanneswilm commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
>  Last year was a “year of preparation” for Vivliostyle, as we set up our development system and launched new projects. This year, we would like to make the most of our achievements and make a big leap
Unclear why "year of preparation" is in quotation marks.

2021-01-07 10:35 UTC, johanneswilm commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
>  Last year was a “year of preparation” for Vivliostyle, as we set up our development system and launched new projects. This year, we would like to make the most of our achievements and make a big leap
recommendation: remove quotation marks.

2021-01-07 11:24 UTC, johanneswilm requested changes

2021-01-07 11:24 UTC, johanneswilm commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +First of all, the update history of [vivliostyle.js](https://github.com/vivliostyle/vivliostyle.js), which is the foundation of the entire project, can be found on the [GitHub release history page](h
"update history" == "changelog"?

Why is the update history the foundation of the project? Or do you mean vivliostyle.js? Also the phrase "First of all" seems a bit out of place. Maybe something like:

"The complete changelog of vivliostyle.js can be found on the [GitHub release history page](https://github.com/vivliostyle/vivliostyle.js/releases). The following two features are especially worth highlighting:"

2021-01-07 11:24 UTC, johanneswilm commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> + Click on “canary” or “stable” to launch the latest version of Vivliostyle Viewer (shown in the figure above), which implements named strings. Clicking on “2019.11” or “2018.2” will launch a previous
It is unclear whether "named strings" are in "canary" or "stable". 

"You can thus compare this two." => "This way you can compare the two."

2021-01-07 11:24 UTC, johanneswilm commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +
If you are familiar with publishing, you may recognize this feature as useful for running headers. ANd it does work for that, but it is not the only way to use "named strings".

2021-01-07 11:24 UTC, johanneswilm commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +In addition, express our deepest gratitude Japan Business Press Co.Ltd, for their support in the development of these versions.
We also want to express our deepest gratitude to Japan Business Press Co.Ltd for their support in the development of these versions.

2021-01-07 11:24 UTC, johanneswilm commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +Finally, let's talk about our main goal, Vivliostyle Pub. vivliostyle.js and Vivliostyle CLI 3.0 that we' ve mentioned so far are all elemental technologies of Vivliostyle Pub. Its requirements speci
"we' ve" => "we've" or "we have"

2021-01-07 15:02 UTC, ogwata commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
>  Last year was a “year of preparation” for Vivliostyle, as we set up our development system and launched new projects. This year, we would like to make the most of our achievements and make a big leap
I see. I'll fix it.

2021-01-07 15:37 UTC, ogwata commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +Happy New Year to you all! Thank you for Vivliostyle again this year.
It is indeed an odd sentence. Your suggestion is accurate, but I want to thank the user as well, so how about the following sentence?

> Vivliostyle would like to thank all the contributors who have collaborated with us on our projects over the last year and all the users of our products.

2021-01-07 15:58 UTC, ogwata commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +First of all, the update history of [vivliostyle.js](https://github.com/vivliostyle/vivliostyle.js), which is the foundation of the entire project, can be found on the [GitHub release history page](h
Thanks for the precise suggestion. How about changing it as follows.

> First, let's talk about vivliostyle.js, the foundation of the entire project. The complete changelog of vivliostyle.js can be found on the GitHub release history page. The following two features are especially worth highlighting:

2021-01-07 16:08 UTC, ogwata commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> + Click on “canary” or “stable” to launch the latest version of Vivliostyle Viewer (shown in the figure above), which implements named strings. Clicking on “2019.11” or “2018.2” will launch a previous
Thanks.

“Click on “canary” or “stable”” => “Click on “canary” and “stable””

> "You can thus compare this two." => "This way you can compare the two."

I see. I'll fix it.

2021-01-07 16:11 UTC, ogwata commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +
I see. I'll fix it.

2021-01-07 16:18 UTC, johanneswilm commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +First of all, the update history of [vivliostyle.js](https://github.com/vivliostyle/vivliostyle.js), which is the foundation of the entire project, can be found on the [GitHub release history page](h
looks good

2021-01-07 16:18 UTC, johanneswilm commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +Happy New Year to you all! Thank you for Vivliostyle again this year.
Ok, yes, this sounds good.

2021-01-07 16:18 UTC, ogwata commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +In addition, express our deepest gratitude Japan Business Press Co.Ltd, for their support in the development of these versions.
I see. I'll fix it.

2021-01-07 16:19 UTC, ogwata commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> +Finally, let's talk about our main goal, Vivliostyle Pub. vivliostyle.js and Vivliostyle CLI 3.0 that we' ve mentioned so far are all elemental technologies of Vivliostyle Pub. Its requirements speci
I see. I'll fix it.

2021-01-07 16:23 UTC, johanneswilm commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> + Click on “canary” and “stable” to launch the latest version of Vivliostyle Viewer (shown in the figure above), which implements named strings. Clicking on “2019.11” or “2018.2” will launch a previou
ok, so the "named strings" are both in canary and in stable? In that case revert to "or and make the entire sentence something like:  

Click on “stable” or "canary" to launch the latest versions of Vivliostyle Viewer (shown in the figure above). Both of them contain the "named strings" feature. Clicking on “2019.11” or “2018.2” will launch an older version of Vivliostyle Viewer (shown in the figure below) without said "named strings" feature. This way you can compare versions of Vivliostyle with or without the "named strings" feature.

2021-01-07 16:27 UTC, ogwata commented on _posts/2021-01-06-new-years-greetings-and-updates-on-vivliostyle.md
> + Click on “canary” and “stable” to launch the latest version of Vivliostyle Viewer (shown in the figure above), which implements named strings. Clicking on “2019.11” or “2018.2” will launch a previou
I see! I'll fix it that way.

2021-01-08 15:10 UTC, MurakamiShinyu approved these changes

2021-01-09 02:12 UTC, merged