Add new ja article
vivliostyle/vivliostyle.org pull request #64
Opened 2021-02-08 13:14 UTC by ogwata

動画は未指定ですが、文章だけご確認ください

2021-02-08 15:47 UTC, MurakamiShinyu commented on _posts/ja/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +以上述べたような v.3へのバージョンアップによって、Vivliostyle CLI の実用性は格段に向上しました。言うまでもなく、CLI は来るべき [Vivliostyle Pub](https://github.com/vivliostyle/vivliostyle-pub) の心臓部とも言える重要コンポーネントです。Vivliostyleの次なるステップに、どうかご注目ください！
「言うまでもなく」と言われても、昨年からのVivliostyleのプレゼンをウォッチしている人以外には、ピンと来ないと思います。「また、このCLIは今年公開を目指す Vivliostyle Pub の…」くらいの表現がよいのでないでしょうか。

2021-02-09 01:05 UTC, spring-raining requested changes

2021-02-09 01:05 UTC, spring-raining commented on _posts/ja/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- 設定ファイル`vivliostyle.config.js`を使って出版物のカスタマイズが可能になった
箇条書きではありますがですます調に揃えてもらえますか？

2021-02-09 05:44 UTC, ogwata commented on _posts/ja/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- 設定ファイル`vivliostyle.config.js`を使って出版物のカスタマイズが可能になった
結末部分を修正し、箇条書きの部分をですます体に改め、動画を追加しました。動画の追加では[この記事](https://webliker.info/52510/)を参考に`video src=`でpathを指定したのですが、こちらのプレビューでは動画として認識されないようです。何が問題なのでしょう？

2021-02-09 05:52 UTC, ogwata commented on _posts/ja/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- 設定ファイル`vivliostyle.config.js`を使って出版物のカスタマイズが可能になった
動画の件、loop属性を追加して自己解決しました。サムネイルは静止画を別途書き出して指定することにします。

2021-02-09 06:05 UTC, ogwata commented on _posts/ja/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- 設定ファイル`vivliostyle.config.js`を使って出版物のカスタマイズが可能になった
動画再生が11秒までで止まってしまいます。controls属性に変更しても同じです。ローカルでは最後まで再生されるので動画自体には問題なさそう。もし解決策があればアドバイスをお願いします。

2021-02-09 06:10 UTC, ogwata commented on _posts/ja/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- 設定ファイル`vivliostyle.config.js`を使って出版物のカスタマイズが可能になった
動画の件、何度か再生を繰り返しているうち、自然に最後まで再生されるようになりました。お騒がせしました。皆さんの環境で問題が発生しないかご確認ください。

2021-02-09 11:27 UTC, johanneswilm commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- Publications can now be customized using the `vivliostyle.config.js` configuration file
I am a little confused about the use of "the" here. Is this a file everyone has already? In that case "the" is probably best. If it is a new file people have to create or obtain, then I would use "a" instead.

2021-02-09 11:29 UTC, johanneswilm commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- The following formats can now be input.
While grammatically correct, outside of rpogramming circles this may sound a bit confusing. How about "The following input formats are now also accepted:" (in addition to the existing ones.

2021-02-09 11:30 UTC, johanneswilm commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- The following formats can now be output.
Similar to the above comment. Maybe change to "We support the following output formats:"

2021-02-09 11:32 UTC, johanneswilm commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +1. overview of the work. (to 0.01 sec.)
overview => Overview

2021-02-09 11:33 UTC, johanneswilm commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +Of the above, [@spring_raining<i class="fas fa-external-link-alt"></i>](https://twitter.com/spring_raining), a contributor, made a short video about the initial file, Vivliostyle Themes, and the buil
"Here is a detailed timesheet of it." => "Here is a detailed timeline of the video:"

2021-02-09 13:55 UTC, spring-raining approved these changes

2021-02-09 13:58 UTC, ogwata commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- Publications can now be customized using the `vivliostyle.config.js` configuration file
Oops!　I always forget that the definite article is different from the indefinite article.

2021-02-09 14:26 UTC, ogwata commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- The following formats can now be input.
I see, so it is better to align the syntax with the previous two items.

2021-02-09 14:35 UTC, MurakamiShinyu commented on _data/project.yml
> +  version: v3.0.1
最新版が v3.0.3 になったので変更してください

2021-02-09 15:09 UTC, ogwata commented on _data/project.yml
> +  version: v3.0.1
後学のために教えていただきたいのですが、この`_data/project.yml`というファイルは、どういう役割のファイルなのでしょう？

2021-02-09 15:32 UTC, MurakamiShinyu commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- Publications can now be customized using a `vivliostyle.config.js` initial file
I think "configuration file" is better than "initial file" for the "vivliostyle.config.js" file.

2021-02-09 16:30 UTC, MurakamiShinyu commented on _data/project.yml
> +  version: v3.0.1
https://vivliostyle.org/getting-started/#vivliostyle-cli
でのバージョンの表示に、このファイルに記述されたものが使われるようになっています。（@yamasy1549 さんが作ってくれたもの）

2021-02-09 16:39 UTC, MurakamiShinyu commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- Publications can now be customized using a `vivliostyle.config.js` initial file
"vivliostyle.config.js" というファイル名からもこれが configuration file であることが分かります。日本語では「設定ファイル」でもよいですが、「構成ファイル」とも訳されます。原稿ファイルの構成などを記述するファイルなので「initial file （初期ファイル）」よりも「configuration file（構成ファイル）」のほうがぴったりだと思います。（日本語記事での「設定ファイル」を「構成ファイル」に直すかどうかは、どちらでもよいと思います。）

2021-02-09 17:03 UTC, johanneswilm commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- The following formats can now be input.
yes, and the term "input formats" is understandable by a slightly larger group than just "inputs".

2021-02-09 17:04 UTC, johanneswilm commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- Publications can now be customized using a `vivliostyle.config.js` initial file
I agree

2021-02-09 17:24 UTC, ogwata commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- Publications can now be customized using a `vivliostyle.config.js` initial file
The command that Vivliostyle CLI uses to generate the configuration file is `init`. So I thought that the generated file should be `initial file` rather than `configuration file`.

However, in `README.md`, the command `init` is described as `create vivliostyle config`. Therefore, `configuration file` might be more correct.


Vivliostyle CLI が設定ファイルを生成するコマンドは`init`です。そこで私は生成されるファイルは「configurationファイル」よりも「initial file」が良いと考えました。

ただし、`README.md` ではコマンド`init`の説明として、`create vivliostyle config`と書いてます。それからすると、`configuration file`の方が正しいのかもしれません。

2021-02-09 17:52 UTC, MurakamiShinyu commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +- Publications can now be customized using a `vivliostyle.config.js` initial file
initコマンドは初期化を行います。それは構成ファイルを初期化するということです。その初期化された構成ファイルに対してユーザーが編集して構成を記述します。

2021-02-10 02:44 UTC, MurakamiShinyu commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +title: Vivliostyle CLI is Major Upgrade to v.3
I think the title "Vivliostyle CLI is Major Upgrade to v.3" is not very good. See the result of Google Translate:

![Screen Shot 2021-02-10 at 11 21 34](https://user-images.githubusercontent.com/3324737/107456160-0f8a0480-6b93-11eb-94e3-c6c1cdf289a0.png)

It sounds that "Vivliostyle CLI" is the name of the major upgrade. That's not true.

"Vivliostyle CLI has been upgraded to v3"

By the way, I prefer "v3" to "v.3".

@johanneswilm Do you have any opinions about these?

2021-02-10 06:02 UTC, johanneswilm commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +title: Vivliostyle CLI is Major Upgrade to v.3
I agree. Maybe even "Vivliostyle CLI v3 represents a major upgrade" or  "Vivliostyle CLI v3 is a major upgrade".

2021-02-10 07:33 UTC, MurakamiShinyu approved these changes

2021-02-10 07:43 UTC, MurakamiShinyu commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +In our first entry of the year, [“New Year's Greetings and Updates on Vivliostyle”](https://vivliostyle.org/blog/2021/01/06/new-years-greetings-and-updates-on-vivliostyle/), We are pleased to announc
日本語では「今年初めてのエントリ「新年のご挨拶とVivliostyleのアップデートについて」の中で、Vivliostyle CLI v3を準備中であることを書きましたが、2月7日、正式にv3.0.0をリリースしたことをお知らせします！」ですが、この英語では
「Vivliostyle CLI v3を準備中であることを書きましたが」の部分が脱落しているようです。コンマのあと大文字の We なのもおかしです

2021-02-10 07:49 UTC, MurakamiShinyu commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +In our first entry of the year, [“New Year's Greetings and Updates on Vivliostyle”](https://vivliostyle.org/blog/2021/01/06/new-years-greetings-and-updates-on-vivliostyle/), We are pleased to announc
"We" の前に "we wrote that Vivliostyle CLI v3 was being prepared. " を入れるといいと思います。

2021-02-10 08:19 UTC, ogwata commented on _posts/2021-02-08-New-release-of-Vivliostyle-CLI-v.3.md
> +In our first entry of the year, [“New Year's Greetings and Updates on Vivliostyle”](https://vivliostyle.org/blog/2021/01/06/new-years-greetings-and-updates-on-vivliostyle/), We are pleased to announc
I guess I was in too much of a hurry. How about the following revision?

In our first entry of the year, “New Year's Greetings and Updates on Vivliostyle”, we wrote that Vivliostyle CLI v3 was being prepared, and we are happy to announce that v3.0.0 was officially released on February 7!

2021-02-10 08:25 UTC, merged